# Generated by Django 5.2b1 on 2025-03-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Ожидание', 'Ожидание'), ('Подтверждено', 'Подтверждено'), ('Отменено', 'Отменено')], default='Ожидание', max_length=20),
        ),
    ]
